<a href="https://colab.research.google.com/github/2401463-sch/SBE3136-Lab-Project-2401463/blob/main/Project_Car_Dealer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Upload your CSV file
from google.colab import files
uploaded = files.upload()

# Read the CSV (replace filename if needed)
df = pd.read_csv(list(uploaded.keys())[0])

# Show first few rows
df.head()

Saving Dataset for Car - Cleaned Dataset .csv to Dataset for Car - Cleaned Dataset  (2).csv

,car_brand,car_make,car_age,ownership,price,total_coe_left_years,coe,dereg_value,road_tax_per_year,omv,arf,total_mileage_km,transmission,engine_cap_cc,power_kw
0,Mazda,Mazda 3 HB 2.0A Sport Sunroof,7,3,58800,3.49,57501,34170.0,1210,21238,21734,104520.0,Auto,1998,121
1,Mazda,Mazda 3 HB 1.5A Deluxe Sunroof,5,1,85800,5.77,25501,28104.0,682,17872,17872,43272.0,Auto,1496,88
2,Mazda,Mazda 3 HB 1.5A Deluxe Sunroof,5,1,79500,5.43,32311,31145.0,682,18342,18342,66400.0,Auto,1496,88
3,Mazda,Mazda 3 HB 1.5A Sunroof,6,1,56800,4.55,25902,20425.0,182,17329,12329,28633.0,Auto,1496,88
4,Mazda,Mazda 3 HB 1.5A Deluxe Sunroof,8,2,42800,2.63,57301,22920.0,682,18108,13108,89000.0,Auto,1496,88

In [2]:
# Convert everything to lowercase (important for consistency)
df['car_make'] = df['car_make'].str.lower()

# Function to standardise model names
def simplify_model(name):
    if 'mazda 3' in name:
        return 'mazda 3'
    elif 'honda vezel' in name:
        return 'honda vezel'
    elif 'toyota corolla' in name:
        return 'toyota corolla altis'
    else:
        return name

# Apply function
df['model_simplified'] = df['car_make'].apply(simplify_model)

# Check results
df[['car_make', 'model_simplified']].head()

                         car_make model_simplified
0   mazda 3 hb 2.0a sport sunroof          mazda 3
1  mazda 3 hb 1.5a deluxe sunroof          mazda 3
2  mazda 3 hb 1.5a deluxe sunroof          mazda 3
3         mazda 3 hb 1.5a sunroof          mazda 3
4  mazda 3 hb 1.5a deluxe sunroof          mazda 3

In [3]:
!pip install landingai

Requirement already satisfied: landingai in /usr/local/lib/python3.12/dist-packages (0.3.49)
Requirement already satisfied: aiofiles<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from landingai) (0.8.0)
Requirement already satisfied: aiohttp<4.0.0,>=3.7.3 in /usr/local/lib/python3.12/dist-packages (from aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (3.13.3)
Requirement already satisfied: bbox-visualizer<0.2.0,>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from landingai) (0.1.0)
Requirement already satisfied: imageio<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imageio[ffmpeg]<3.0.0,>=2.0.0->landingai) (2.37.3)
Requirement already satisfied: numpy<2.0.0,>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from landingai) (1.26.4)
Requirement already satisfied: opencv-python<5.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from landingai) (4.11.0.86)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from landingai) (2.2.2)
Requirement already satisfied: pillow<11.0,>=9.0 in /usr/local/lib/python3.12/dist-packages (from landingai) (10.4.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from landingai) (2.12.3)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from landingai) (2.13.1)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from landingai) (2.32.4)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from landingai) (1.0.0)
Requirement already satisfied: segmentation-mask-overlay<0.4.0,>=0.3.4 in /usr/local/lib/python3.12/dist-packages (from landingai) (0.3.4)
Requirement already satisfied: tenacity<9.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from landingai) (8.5.0)
Requirement already satisfied: tqdm<5.0.0,>=4.64.0 in /usr/local/lib/python3.12/dist-packages (from landingai) (4.67.3)
Requirement already satisfied: urllib3<2.0.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from landingai) (1.26.20)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.7.3->aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.7.3->aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.7.3->aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.7.3->aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.7.3->aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.7.3->aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.7.3->aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (1.23.0)
Requirement already satisfied: aiodns>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (4.0.0)
Requirement already satisfied: Brotli>=1.2 in /usr/local/lib/python3.12/dist-packages (from aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (1.2.0)
Requirement already satisfied: backports.zstd in /usr/local/lib/python3.12/dist-packages (from aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (1.3.0)
Requirement already satisfied: imageio-ffmpeg in /usr/local/lib/python3.12/dist-packages (from imageio[ffmpeg]<3.0.0,>=2.0.0->landingai) (0.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from imageio[ffmpeg]<3.0.0,>=2.0.0->landingai) (5.9.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->landingai) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->landingai) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->landingai) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->landingai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->landingai) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->landingai) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->landingai) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.3.1->landingai) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->landingai) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->landingai) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->landingai) (2026.2.25)
Requirement already satisfied: matplotlib>=3.4.2 in /usr/local/lib/python3.12/dist-packages (from segmentation-mask-overlay<0.4.0,>=0.3.4->landingai) (3.10.0)
Requirement already satisfied: opencv-python-headless>=4.5.3 in /usr/local/lib/python3.12/dist-packages (from segmentation-mask-overlay<0.4.0,>=0.3.4->landingai) (4.11.0.86)
Requirement already satisfied: pycares<6,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from aiodns>=3.3.0->aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (5.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.2->segmentation-mask-overlay<0.4.0,>=0.3.4->landingai) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.2->segmentation-mask-overlay<0.4.0,>=0.3.4->landingai) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.2->segmentation-mask-overlay<0.4.0,>=0.3.4->landingai) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.2->segmentation-mask-overlay<0.4.0,>=0.3.4->landingai) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.2->segmentation-mask-overlay<0.4.0,>=0.3.4->landingai) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.2->segmentation-mask-overlay<0.4.0,>=0.3.4->landingai) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.0->landingai) (1.17.0)
Requirement already satisfied: cffi>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pycares<6,>=5.0.0->aiodns>=3.3.0->aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.5.0->pycares<6,>=5.0.0->aiodns>=3.3.0->aiohttp[speedups]<4.0.0,>=3.7.3->landingai) (3.0)

In [4]:
from landingai.predict import Predictor

# Replace with your actual values
endpoint_id = "3ad32ebe-da0e-4ddf-a7f9-ec379fded40e"
api_key = "land_sk_gcSn8WaIHYgNYTkH2AczetyYcR5nsPNd04ATJHgyNBQDlIDIo1"

predictor = Predictor(endpoint_id, api_key=api_key)

In [20]:
from PIL import Image

# Upload image
from google.colab import files
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Open image
image = Image.open(image_path)

# Predict
result = predictor.predict(image)

# Extract label
predicted_label = result[0].label_name.lower()
print("Raw:", predicted_label)

# Simplify
predicted_label = simplify_model(predicted_label)
print("Simplified:", predicted_label)

# Filter dataset
filtered_df = df[df['model_simplified'] == predicted_label]

# Show result
filtered_df.head()

Saving Slide17.JPG to Slide17.JPG
Raw: mazda 3
Simplified: mazda 3

,car_brand,car_make,car_age,ownership,price,total_coe_left_years,coe,dereg_value,road_tax_per_year,omv,arf,total_mileage_km,transmission,engine_cap_cc,power_kw,model_simplified
0,Mazda,mazda 3 hb 2.0a sport sunroof,7,3,58800,3.49,57501,34170.0,1210,21238,21734,104520.0,Auto,1998,121,mazda 3
1,Mazda,mazda 3 hb 1.5a deluxe sunroof,5,1,85800,5.77,25501,28104.0,682,17872,17872,43272.0,Auto,1496,88,mazda 3
2,Mazda,mazda 3 hb 1.5a deluxe sunroof,5,1,79500,5.43,32311,31145.0,682,18342,18342,66400.0,Auto,1496,88,mazda 3
3,Mazda,mazda 3 hb 1.5a sunroof,6,1,56800,4.55,25902,20425.0,182,17329,12329,28633.0,Auto,1496,88,mazda 3
4,Mazda,mazda 3 hb 1.5a deluxe sunroof,8,2,42800,2.63,57301,22920.0,682,18108,13108,89000.0,Auto,1496,88,mazda 3

In [46]:
# Make sure filtered_df is used
data = filtered_df.copy()
data = data.dropna()

# Separate features + target
features = [
    "car_age",
    "ownership",
    "total_mileage_km",
    "engine_cap_cc",
    "power_kw",
    "transmission",
    "coe",
    "total_coe_left_years",
    "dereg_value"
]

X = data[features]
y = data['price']

# Encode
X = pd.get_dummies(X, drop_first=True)

# Train model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

# NOW predict using THIS filtered dataset
sample = X.iloc[0:1]
predicted_price = model.predict(sample)

print("Predicted Price:", predicted_price[0])

Predicted Price: 53350.94843887634

In [63]:
# Example user input (you can change values)
user_input = {
    "car_age": 10,
    "ownership": 1,
    "coe": 40000,
    "dereg_value": 30000,
    "total_mileage_km": 60000,
    "engine_cap_cc": 1500,
    "power_kw": 85,
    "transmission": "auto"
}

In [64]:
user_df = pd.DataFrame([user_input])

In [65]:
print(user_df)
print("Columns:", user_df.columns)

   car_age  ownership    coe  dereg_value  total_mileage_km  engine_cap_cc  \
0       10          1  40000        30000             60000           1500

   power_kw transmission
0        85         auto
Columns: Index(['car_age', 'ownership', 'coe', 'dereg_value', 'total_mileage_km',
       'engine_cap_cc', 'power_kw', 'transmission'],
      dtype='object')

In [66]:
user_df = pd.get_dummies(user_df)

# VERY IMPORTANT
print("Before align:", user_df.shape)

user_df = user_df.reindex(columns=X.columns, fill_value=0)

print("After align:", user_df.shape)

Before align: (1, 8)
After align: (1, 8)

In [67]:
predicted_price = model.predict(user_df)

print("Predicted Price:", predicted_price[0])

Predicted Price: 25336.72436239865

In [68]:
!pip install gradio

Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (5.50.0)
Collecting aiofiles<25.0,>=22.0 (from gradio)
  Downloading aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.12.1)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.135.1)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.14.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.7.1)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.26.4)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.0)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (10.4.0)
Requirement already satisfied: pydantic<=2.12.3,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.12.3)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.22)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.15.6)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.24.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.42.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (2025.3.0)
Requirement already satisfied: websockets<16.0,>=13.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0,>=3.0->gradio) (3.11)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (3.25.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.4.2)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=2.12.3,>=2.0->gradio) (2.41.4)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0,>=0.12->gradio) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0,>=0.12->gradio) (0.1.2)
Downloading aiofiles-24.1.0-py3-none-any.whl (15 kB)
Installing collected packages: aiofiles
  Attempting uninstall: aiofiles
    Found existing installation: aiofiles 0.8.0
    Uninstalling aiofiles-0.8.0:
      Successfully uninstalled aiofiles-0.8.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
landingai 0.3.49 requires aiofiles<1.0.0,>=0.7.0, but you have aiofiles 24.1.0 which is incompatible.
Successfully installed aiofiles-24.1.0

In [73]:
import gradio as gr

def predict_price(image, car_age, mileage, coe, engine_cap, power, dereg):

    # Convert image
    from PIL import Image
    image = Image.fromarray(image)

    # LandingLens prediction
    result = predictor.predict(image)
    label = result[0].label_name.lower()
    label = simplify_model(label)

    # Filter dataset
    filtered_df = df[df['model_simplified'] == label].dropna()

    # Features
    features = [
        "car_age", "ownership", "total_mileage_km",
        "engine_cap_cc", "power_kw", "transmission",
        "coe", "dereg_value"
    ]

    X = filtered_df[features]
    y = filtered_df['price']

    X = pd.get_dummies(X, drop_first=True)

    from sklearn.linear_model import LinearRegression
    model = LinearRegression()
    model.fit(X, y)

    # User input
    user_input = {
        "car_age": car_age,
        "ownership": 1,
        "total_mileage_km": mileage,
        "engine_cap_cc": engine_cap,
        "power_kw": power,
        "transmission": "auto",
        "coe": coe,
        "dereg_value": dereg
    }

    user_df = pd.DataFrame([user_input])
    user_df = pd.get_dummies(user_df)
    user_df = user_df.reindex(columns=X.columns, fill_value=0)

    price = model.predict(user_df)[0]

    return f"Model: {label} | Predicted Price: ${price:.2f}"

In [74]:
interface = gr.Interface(
    fn=predict_price,
    inputs=[
        gr.Image(type="numpy"),
        gr.Number(label="Car Age"),
        gr.Number(label="Mileage"),
        gr.Number(label="COE"),
        gr.Number(label="Engine CC"),
        gr.Number(label="Power (kW)"),
        gr.Number(label="Dereg Value")
    ],
    outputs="text",
    title="Car Price Predictor"
)

interface.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://52b4b71e3e25778f33.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)